# Generated by Django 6.0.4 on 2026-04-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dop_stat_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop_stat_name', models.CharField(max_length=50, verbose_name='Дополнительная характеристика')),
            ],
            options={
                'verbose_name': 'Тип доп. стата',
                'verbose_name_plural': 'Типы доп. статов',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=50, verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Weapon_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type_name', models.CharField(max_length=50, verbose_name='Тип оружия')),
            ],
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
            },
        ),
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifacts_image', models.ImageField(blank=True, null=True, upload_to='artifacts_image/', verbose_name='Изображение сета артефактов')),
                ('name', models.CharField(max_length=100, verbose_name='Название сета артефактов')),
                ('dop_stat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Значение дополнительной характеристики')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание сета артефактов')),
                ('dop_stat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.dop_stat_type', verbose_name='Дополнительная характеристика')),
            ],
            options={
                'verbose_name': 'Сет артефакта',
                'verbose_name_plural': 'Сеты артефактов',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='character_image/', verbose_name='Изображение персонажа')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('health', models.IntegerField(verbose_name='Здоровье')),
                ('attack_power', models.IntegerField(verbose_name='Сила атаки')),
                ('protection', models.IntegerField(verbose_name='Защита')),
                ('mastery_elements', models.IntegerField(verbose_name='Мастерство стихий')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание персонажа')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.element', verbose_name='Элемент')),
                ('type_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.weapon_type', verbose_name='Тип оружия')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_image', models.ImageField(blank=True, null=True, upload_to='weapon_image/', verbose_name='Изображение оружия')),
                ('name', models.CharField(max_length=100, verbose_name='Название оружия')),
                ('dop_stat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Значение дополнительной характеристики')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание оружия')),
                ('dop_stat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.dop_stat_type', verbose_name='Дополнительная характеристика')),
                ('type_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.weapon_type', verbose_name='Тип оружия')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружия',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сборки')),
                ('artifacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.artifacts', verbose_name='Артефакты')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.character', verbose_name='Персонаж')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.weapon', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
            },
        ),
    ]
