# Generated by Django 6.0.3 on 2026-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружия'},
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='dop_stat',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Значение дополнительной характеристики'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dop_stat',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Значение дополнительной характеристики'),
        ),
    ]
