# Generated by Django 6.0.3 on 2026-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0002_alter_weapon_options_alter_artifacts_dop_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifacts',
            name='dop_stat',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Значение дополнительной характеристики'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dop_stat',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Значение дополнительной характеристики'),
        ),
    ]
