[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/bin/sh -c "envsubst '\$PORT' < /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.tmp && cp /etc/nginx/sites-available/default.tmp /etc/nginx/sites-available/default && nginx -g 'daemon off;'"
autostart=true
autorestart=true

[program:gunicorn]
command=gunicorn --pythonpath . first_project.wsgi:application --bind 127.0.0.1:8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/gunicorn.log
stderr_logfile=/var/log/gunicorn.err